# Generated by Django 4.2.9 on 2024-01-31 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='from_email',
            field=models.CharField(default='discount@nebulous.tech', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='from_name',
            field=models.CharField(default='Nebulous Tech', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='html',
            field=models.TextField(default='HTML'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
