# Generated by Django 4.2.9 on 2024-02-01 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_deploymenttemplate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeploymentTemplate',
            new_name='Deployment',
        ),
    ]
