# Generated by Django 4.2.9 on 2024-02-01 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_deployment_deployment_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailTemplate',
            new_name='Email_Template',
        ),
    ]
