# Generated by Django 4.2.9 on 2024-02-01 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_rename_emailtemplate_email_template'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email_Template',
            new_name='EmailTemplate',
        ),
    ]
