# Generated by Django 4.2.9 on 2024-02-01 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_remove_deployment_contact_list_mailinglist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='mailing_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mailing.mailinglist'),
        ),
    ]
