# Generated by Django 4.2.9 on 2024-02-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_alter_deployment_mailing_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('contact_list', models.ManyToManyField(to='mailing.contact')),
            ],
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='contact_list',
            field=models.ManyToManyField(to='mailing.contactgroup'),
        ),
    ]
