# Generated by Django 4.2.9 on 2024-02-01 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0010_contactgroup_alter_mailinglist_contact_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailinglist',
            old_name='contact_list',
            new_name='group_list',
        ),
    ]
