# Generated by Django 4.2.9 on 2024-02-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0011_rename_contact_list_mailinglist_group_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglist',
            name='group_list',
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='contact_list',
            field=models.ManyToManyField(to='mailing.contact'),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='select_all',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ContactGroup',
        ),
    ]
