# Generated by Django 4.2.16 on 2024-10-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0013_remove_mailinglist_select_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='from_email',
            field=models.CharField(default='contact@nebulous.tech', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='from_name',
            field=models.CharField(default='nebulous.tech', max_length=255),
        ),
    ]
