# Generated by Django 4.2.16 on 2024-10-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images/')),
                ('date', models.DateTimeField()),
                ('people', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
    ]
