# Generated by Django 4.2.16 on 2024-10-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='model', to='main_site.person'),
        ),
        migrations.AlterField(
            model_name='image',
            name='photographer',
            field=models.ManyToManyField(blank=True, related_name='photographer', to='main_site.person'),
        ),
    ]
