# Generated by Django 4.2.16 on 2024-10-09 00:19

from django.db import migrations, models
import main_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_alter_image_people_alter_image_photographer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=main_site.models.my_func),
        ),
    ]
