# Generated by Django 4.2.16 on 2024-10-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.RemoveField(
            model_name='image',
            name='people',
        ),
        migrations.AddField(
            model_name='image',
            name='people',
            field=models.ManyToManyField(to='main_site.person'),
        ),
    ]
