# Generated by Django 4.2.16 on 2024-10-07 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_person_image_location_remove_image_people_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'People'},
        ),
    ]
