# Generated by Django 4.2.16 on 2024-10-09 00:21

from django.db import migrations, models
import main_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default=main_site.models.my_func, upload_to='images'),
        ),
    ]
